title: "Biometix"
title_separator: "|"
subtitle: "BQAT"
description: "A Biometric Quality Assessment Tool by Biometix Pty Ltd"
logo: "logo.png"
color-scheme: biometix
aux_links:
  "Biometix on Github":
    - "//github.com/Biometix"

baseurl: /biometix.github.io/
url: https://biometix.github.io
domain: biometix.github.io
repository: Biometix/biometix.github.io
heading_anchors: true

lsi: false
safe: true
source: biometix.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: just-the-docs

plugins:
  - "jekyll-github-metadata"
